INSERT INTO shoes (name, brand, colour, size, price, in_stock, img_src)
VALUES
    ('Glam heels', 'LODI', 'Grey', 6, 799, 12, '/images/shoes/grey1.jpg'),
    ('Divine soles', 'LODI', 'Black', 5, 559, 8, '/images/shoes/black1.jpg'),
    ('Elegant elevate', 'LODI', 'Red', 5, 299, 5, '/images/shoes/red1.jpg'),
    ('Vogue stilettos', 'LODI', 'Green', 4, 649, 3, '/images/shoes/green1.jpg'),
    ('Sole sculpt', 'LUXE', 'Black', 6, 664, 7, '/images/shoes/black2.jpg'),
    ('Enchant heels', 'LUXE', 'Blue', 5, 559, 14, '/images/shoes/blue1.jpg'),
    ('Posh pumps', 'LUXE', 'Grey', 9, 649, 4, '/images/shoes/grey2.jpg'),
    ('Radiant strides', 'LUXE', 'Orange', 5, 799, 9, '/images/shoes/orange1.jpg'),
    ('Allure heels', 'STILETTOS', 'Grey', 6, 899, 11, '/images/shoes/grey3.jpg'),
    ('Graceful gait', 'STILETTOS', 'Black', 5, 899, 5, '/images/shoes/black3.jpg'),
    ('Svelte sole', 'STILETTOS', 'Red', 4, 551, 6, '/images/shoes/red2.jpg'),
    ('Regal steps', 'DAZZLESTEPS', 'Black', 6, 699, 10, '/images/shoes/black4.jpg'),
    ('Opulent outsteps', 'DAZZLESTEPS', 'Blue', 5, 250, 4, '/images/shoes/blue2.jpg'),
    ('Velvet verve', 'DAZZLESTEPS', 'Orange', 4, 899, 8, '/images/shoes/orange2.jpg'),
    ('Radiance rises', 'VIXENS', 'Green', 6, 899, 12, '/images/shoes/green2.jpg'),
    ('Queenly quotient', 'VIXENS', 'Red', 5, 999, 5, '/images/shoes/red3.jpg'),
    ('Celestial chic', 'VIXENS', 'Green', 4, 299, 9, '/images/shoes/green3.jpg'),
    ('Sole serenity', 'DIAMONDHEIGHTS', 'Blue', 6, 599, 7, '/images/shoes/blue3.jpg'),
    ('Luxe lift', 'DIAMONDHEIGHTS', 'Orange', 5, 399, 3, '/images/shoes/orange3.jpg'),
    ('Eleganza heels', 'DIAMONDHEIGHTS', 'Red', 4, 999, 10, '/images/shoes/red4.jpg');